export type HubNodeStatus =
  | "operational"
  | "observing"
  | "building"
  | "private";

export type HubNodeKind = "person" | "zone" | "group" | "destination";

export type HubNode = {
  id: string;
  label: string;
  shortLabel?: string;
  eyebrow: string;
  description: string;
  kind: HubNodeKind;
  status: HubNodeStatus;
  children?: string[];
  href?: string;
};

export const rootNodeId = "edward";

export const hubNodes: Record<string, HubNode> = {
  edward: {
    id: "edward",
    label: "Main Hub",
    shortLabel: "HUB",
    eyebrow: "Ecosystem",
    description: "A living index of work, systems, projects, and notes.",
    kind: "person",
    status: "operational",
    children: ["troa", "ryu", "personal", "homelab", "projects"],
  },
  troa: {
    id: "troa",
    label: "TROA",
    eyebrow: "Organization",
    description: "Technology, platforms, operations, and technical leadership.",
    kind: "zone",
    status: "observing",
    children: [
      "troa-infrastructure",
      "troa-software",
      "troa-devops",
      "troa-cto",
      "troa-community",
    ],
  },
  "troa-infrastructure": {
    id: "troa-infrastructure",
    label: "Infrastructure",
    eyebrow: "TROA / Systems",
    description: "A public-safe abstraction of the operational environment.",
    kind: "group",
    status: "operational",
    children: [
      "troa-edge",
      "troa-network",
      "troa-compute",
      "troa-virtualization",
      "troa-storage",
      "troa-access",
    ],
  },
  "troa-edge": {
    id: "troa-edge",
    label: "Edge & DNS",
    eyebrow: "Infrastructure",
    description: "Connectivity, public routing, DNS, and edge policy.",
    kind: "destination",
    status: "operational",
  },
  "troa-network": {
    id: "troa-network",
    label: "Network",
    eyebrow: "Infrastructure",
    description: "Segmentation, switching, wireless, and traffic boundaries.",
    kind: "destination",
    status: "operational",
  },
  "troa-compute": {
    id: "troa-compute",
    label: "Compute",
    eyebrow: "Infrastructure",
    description: "Physical capacity represented without publishing host details.",
    kind: "destination",
    status: "observing",
  },
  "troa-virtualization": {
    id: "troa-virtualization",
    label: "Virtualization",
    eyebrow: "Infrastructure",
    description: "Workload placement, virtual machines, and resource policy.",
    kind: "destination",
    status: "operational",
  },
  "troa-storage": {
    id: "troa-storage",
    label: "Storage & Backup",
    eyebrow: "Infrastructure",
    description: "Durable storage, replication, recovery, and continuity.",
    kind: "destination",
    status: "operational",
  },
  "troa-access": {
    id: "troa-access",
    label: "Remote Access",
    eyebrow: "Infrastructure",
    description: "Private administrative access and support tooling.",
    kind: "destination",
    status: "private",
  },
  "troa-software": {
    id: "troa-software",
    label: "Software",
    eyebrow: "TROA / Products",
    description: "Public applications, internal tools, and integrations.",
    kind: "group",
    status: "building",
    children: [
      "troa-public-apps",
      "troa-internal-tools",
      "troa-community-platforms",
      "troa-integrations",
    ],
  },
  "troa-public-apps": {
    id: "troa-public-apps",
    label: "Public Apps",
    eyebrow: "Software",
    description: "Member and community-facing product experiences.",
    kind: "destination",
    status: "building",
  },
  "troa-internal-tools": {
    id: "troa-internal-tools",
    label: "Internal Tools",
    eyebrow: "Software",
    description: "Private workflows for administration and operations.",
    kind: "destination",
    status: "private",
  },
  "troa-community-platforms": {
    id: "troa-community-platforms",
    label: "Community Platforms",
    eyebrow: "Software",
    description: "Spaces and services that support the community.",
    kind: "destination",
    status: "operational",
  },
  "troa-integrations": {
    id: "troa-integrations",
    label: "Integrations",
    eyebrow: "Software",
    description: "Connections between products, data, and third-party services.",
    kind: "destination",
    status: "observing",
  },
  "troa-devops": {
    id: "troa-devops",
    label: "DevOps",
    eyebrow: "TROA / Delivery",
    description: "The path from source to reliable production systems.",
    kind: "group",
    status: "operational",
    children: [
      "troa-source",
      "troa-cicd",
      "troa-containers",
      "troa-environments",
      "troa-observability",
      "troa-security-ops",
    ],
  },
  "troa-source": {
    id: "troa-source",
    label: "Source",
    eyebrow: "DevOps",
    description: "Repositories, review, and code ownership.",
    kind: "destination",
    status: "operational",
  },
  "troa-cicd": {
    id: "troa-cicd",
    label: "CI / CD",
    eyebrow: "DevOps",
    description: "Checks, builds, releases, and deployment automation.",
    kind: "destination",
    status: "building",
  },
  "troa-containers": {
    id: "troa-containers",
    label: "Containers",
    eyebrow: "DevOps",
    description: "Packaged services and repeatable runtime environments.",
    kind: "destination",
    status: "operational",
  },
  "troa-environments": {
    id: "troa-environments",
    label: "Environments",
    eyebrow: "DevOps",
    description: "Development, quality, operations, and production boundaries.",
    kind: "destination",
    status: "observing",
  },
  "troa-observability": {
    id: "troa-observability",
    label: "Observability",
    eyebrow: "DevOps",
    description: "Health, performance, events, and operational awareness.",
    kind: "destination",
    status: "operational",
  },
  "troa-security-ops": {
    id: "troa-security-ops",
    label: "Security Ops",
    eyebrow: "DevOps",
    description: "Access, patching, risk controls, and response practices.",
    kind: "destination",
    status: "private",
  },
  "troa-cto": {
    id: "troa-cto",
    label: "CTO Operations",
    shortLabel: "CTO Ops",
    eyebrow: "TROA / Leadership",
    description: "Architecture, planning, risk, documentation, and delivery.",
    kind: "group",
    status: "building",
    children: [
      "troa-architecture",
      "troa-roadmap",
      "troa-risk",
      "troa-documentation",
      "troa-team",
      "troa-assets",
    ],
  },
  "troa-architecture": {
    id: "troa-architecture",
    label: "Architecture",
    eyebrow: "CTO Operations",
    description: "System boundaries, technical direction, and design decisions.",
    kind: "destination",
    status: "operational",
  },
  "troa-roadmap": {
    id: "troa-roadmap",
    label: "Roadmap",
    eyebrow: "CTO Operations",
    description: "Sequencing technical work against organizational priorities.",
    kind: "destination",
    status: "building",
  },
  "troa-risk": {
    id: "troa-risk",
    label: "Risk & Security",
    eyebrow: "CTO Operations",
    description: "Operational risk, resilience, privacy, and security posture.",
    kind: "destination",
    status: "observing",
  },
  "troa-documentation": {
    id: "troa-documentation",
    label: "Documentation",
    eyebrow: "CTO Operations",
    description: "Runbooks, diagrams, standards, and institutional memory.",
    kind: "destination",
    status: "building",
  },
  "troa-team": {
    id: "troa-team",
    label: "Team & Delivery",
    eyebrow: "CTO Operations",
    description: "Planning, communication, review, and sustainable execution.",
    kind: "destination",
    status: "operational",
  },
  "troa-assets": {
    id: "troa-assets",
    label: "Vendors & Assets",
    eyebrow: "CTO Operations",
    description: "Licensing, vendors, equipment, and lifecycle decisions.",
    kind: "destination",
    status: "private",
  },
  "troa-community": {
    id: "troa-community",
    label: "Community",
    eyebrow: "TROA / Mission",
    description: "The people and programs the technology exists to support.",
    kind: "group",
    status: "operational",
    children: ["troa-programs", "troa-members", "troa-communications"],
  },
  "troa-programs": {
    id: "troa-programs",
    label: "Programs",
    eyebrow: "Community",
    description: "Initiatives, events, and community services.",
    kind: "destination",
    status: "operational",
  },
  "troa-members": {
    id: "troa-members",
    label: "Members",
    eyebrow: "Community",
    description: "Identity, access, participation, and support.",
    kind: "destination",
    status: "private",
  },
  "troa-communications": {
    id: "troa-communications",
    label: "Communications",
    eyebrow: "Community",
    description: "Updates, channels, publishing, and outreach.",
    kind: "destination",
    status: "operational",
  },
  ryu: {
    id: "ryu",
    label: "Ryu Legal",
    eyebrow: "Organization",
    description: "Client experience, legal workflows, software, and operations.",
    kind: "zone",
    status: "building",
    children: [
      "ryu-site",
      "ryu-workflows",
      "ryu-software",
      "ryu-infrastructure",
      "ryu-documents",
    ],
  },
  "ryu-site": {
    id: "ryu-site",
    label: "Website",
    eyebrow: "Ryu Legal",
    description: "The public client-facing web experience.",
    kind: "destination",
    status: "building",
  },
  "ryu-workflows": {
    id: "ryu-workflows",
    label: "Legal Workflows",
    eyebrow: "Ryu Legal",
    description: "Operational pathways and client service processes.",
    kind: "destination",
    status: "observing",
  },
  "ryu-software": {
    id: "ryu-software",
    label: "Software",
    eyebrow: "Ryu Legal",
    description: "Purpose-built and configured tools supporting the practice.",
    kind: "destination",
    status: "building",
  },
  "ryu-infrastructure": {
    id: "ryu-infrastructure",
    label: "Infrastructure",
    eyebrow: "Ryu Legal",
    description: "Hosting, deployment, access, and operational continuity.",
    kind: "destination",
    status: "private",
  },
  "ryu-documents": {
    id: "ryu-documents",
    label: "Documents",
    eyebrow: "Ryu Legal",
    description: "Secure document workflows and knowledge systems.",
    kind: "destination",
    status: "private",
  },
  personal: {
    id: "personal",
    label: "ES",
    shortLabel: "ES",
    eyebrow: "Identity",
    description: "Profile, writing, résumé, notes, and public links.",
    kind: "zone",
    status: "operational",
    children: ["profile", "resume", "readme", "blog", "links"],
  },
  profile: {
    id: "profile",
    label: "Profile",
    eyebrow: "ES",
    description: "Product engineering, technical leadership, and selected work.",
    kind: "destination",
    status: "operational",
    href: "https://www.edsong.xyz",
  },
  resume: {
    id: "resume",
    label: "Résumé",
    eyebrow: "ES",
    description: "Experience, roles, and capabilities.",
    kind: "destination",
    status: "operational",
  },
  readme: {
    id: "readme",
    label: "README",
    eyebrow: "ES",
    description: "A terse index of current work and interests.",
    kind: "destination",
    status: "building",
  },
  blog: {
    id: "blog",
    label: "Blog & Notes",
    eyebrow: "ES",
    description: "Build logs, technical notes, and longer reflections.",
    kind: "destination",
    status: "building",
  },
  links: {
    id: "links",
    label: "Links",
    eyebrow: "ES",
    description: "Profiles, contact paths, and useful destinations.",
    kind: "destination",
    status: "operational",
  },
  homelab: {
    id: "homelab",
    label: "Homelab",
    eyebrow: "ES / Systems",
    description: "Servers, self-hosted software, and operational tools.",
    kind: "zone",
    status: "observing",
    children: [
      "personal-systems",
      "coolify",
      "penpot",
      "jellyfin",
      "uptime-kuma",
      "open-source",
    ],
  },
  "personal-systems": {
    id: "personal-systems",
    label: "Servers & Network",
    eyebrow: "Homelab",
    description: "Private compute, networking, storage, and backups.",
    kind: "destination",
    status: "private",
  },
  coolify: {
    id: "coolify",
    label: "Coolify",
    eyebrow: "Homelab",
    description: "Application deployment and lifecycle management.",
    kind: "destination",
    status: "operational",
  },
  penpot: {
    id: "penpot",
    label: "Penpot",
    eyebrow: "Homelab",
    description: "Open-source interface design and collaboration.",
    kind: "destination",
    status: "operational",
  },
  jellyfin: {
    id: "jellyfin",
    label: "Jellyfin",
    eyebrow: "Homelab",
    description: "Private media library and streaming.",
    kind: "destination",
    status: "private",
  },
  "uptime-kuma": {
    id: "uptime-kuma",
    label: "Uptime Kuma",
    shortLabel: "Kuma",
    eyebrow: "Homelab",
    description: "Service health and availability signals.",
    kind: "destination",
    status: "operational",
  },
  "open-source": {
    id: "open-source",
    label: "Open Source",
    eyebrow: "Homelab",
    description: "Selected tools operated, evaluated, or extended.",
    kind: "destination",
    status: "observing",
  },
  projects: {
    id: "projects",
    label: "Projects & Lab",
    shortLabel: "Projects",
    eyebrow: "Making",
    description: "Live products, experiments, design studies, and archives.",
    kind: "zone",
    status: "building",
    children: [
      "claimchain",
      "live-projects",
      "experiments",
      "design-studies",
      "archive",
    ],
  },
  claimchain: {
    id: "claimchain",
    label: "ClaimChain",
    eyebrow: "Projects",
    description: "A live product and ongoing engineering project.",
    kind: "destination",
    status: "building",
  },
  "live-projects": {
    id: "live-projects",
    label: "Live Projects",
    eyebrow: "Projects",
    description: "Publicly available work and active deployments.",
    kind: "destination",
    status: "operational",
  },
  experiments: {
    id: "experiments",
    label: "Experiments",
    eyebrow: "Projects",
    description: "Small technical studies and one-day builds.",
    kind: "destination",
    status: "observing",
  },
  "design-studies": {
    id: "design-studies",
    label: "Design Studies",
    eyebrow: "Projects",
    description: "Interface concepts, maps, and visual explorations.",
    kind: "destination",
    status: "building",
  },
  archive: {
    id: "archive",
    label: "Archive",
    eyebrow: "Projects",
    description: "Completed and paused work worth keeping discoverable.",
    kind: "destination",
    status: "private",
  },
};

export const statusLabels: Record<HubNodeStatus, string> = {
  operational: "Operational",
  observing: "Observing",
  building: "Building",
  private: "Private",
};

export function getParentId(nodeId: string): string | null {
  for (const node of Object.values(hubNodes)) {
    if (node.children?.includes(nodeId)) return node.id;
  }
  return null;
}

export function getNodePath(nodeId: string): HubNode[] {
  const path: HubNode[] = [];
  let currentId: string | null = nodeId;
  while (currentId) {
    path.unshift(hubNodes[currentId]);
    currentId = getParentId(currentId);
  }
  return path;
}

export function getChildren(nodeId: string): HubNode[] {
  return (hubNodes[nodeId].children ?? []).map((id) => hubNodes[id]);
}
